# 默认80端口访问
server:
  port: 80

# 不要使用tab输入空格
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oa-sys
    username: root
    password: a
    driver-class-name: com.mysql.jdbc.Driver

# 配置 静态资源路径
  resources:
    staticLocations:
      file:/d:/ppt/,
      classpath:/static/,
      classpath:/META-INF/resources/,
      classpath:/resources/,
      classpath:/public/

# 配置文件上传大小与请求大小限制
  servlet:
    multipart:
      max-file-size: 100000000000000
      max-request-size: 100000000000000

# 配置邮件发送
  mail:
    host: smtp.qq.com
    username: yuan16699@qq.com
    password: cpwfmlsaetdseabb
    default-encoding: UTF-8
    
  redis:
    database: 0           #redis数据库索引(默认为0)
    host: 127.0.0.1       #Redis服务器地址
    port: 6379            #服务器端口
    password:             #默认为空
    timeout: 60000         #连接超时时间(毫秒)
    jedis:
      pool:
        max-active: 200   #连接池最大连接数(使用负值表示没有限制)
        max-wait: -1      # 连接池最大阻塞等待时间
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接

mail:
  formMail:
    addr: yuan16699@qq.com
    resetPwdEmailContent: 您好，欢迎使用重置密码服务，您的验证码为：
    addAdminContent: 您好，欢迎使用管理员添加功能，您的验证码为：
    resetEmEmailContent: 您好，欢迎使用重置邮箱服务，您的验证码为：
    resetTelEmailContent: 您好，欢迎使用重置电话服务，您的验证码为：
    businessRegisterEmailContent: 您好，欢迎使用注册服务，您的验证码为：

# 配置debug日志输出
logging:
  level:
    com:
      sllp: debug